import React from "react";

const About = () => {
    return (
        <div className="mb-20">
            <h1 className="sm:text-4xl text-2xl font-bold my-6 text-gray-900">About</h1>
            <p className="mx-auto leading-relaxed text-base mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies turpis eget dolor vehicula, vitae dignissim nisl finibus. Integer vehicula suscipit ante, sit amet efficitur lacus lacinia id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam convallis libero vel nisi porta, quis dapibus nulla ultrices. Sed vel ipsum sit amet neque placerat vehicula ac nec nulla. Phasellus id arcu eget urna ultricies consequat vel non libero. Donec rhoncus sapien vitae velit dapibus, a commodo ipsum tristique. Etiam auctor risus vel felis consequat, sit amet consequat felis malesuada. Cras posuere commodo lacinia. Duis sodales velit non tellus pulvinar, a volutpat orci tempor. Curabitur ut hendrerit libero. Duis ac odio malesuada, consectetur nisi at, cursus semper libero. Quisque ut hendrerit nulla.</p>
            <p className="mx-auto leading-relaxed text-base mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec mauris vel risus fermentum hendrerit nec non nulla. Nulla sollicitudin bibendum arcu eget dapibus. Maecenas quis magna vel enim dignissim aliquet. Integer ac felis nec purus dapibus luctus. Nam vitae dolor vel metus finibus ultrices nec et enim. Sed sit amet eros nec tortor tincidunt elementum. In hac habitasse platea dictumst. Integer non diam vitae ex consectetur tincidunt. Nunc congue, quam id vehicula consequat, ipsum ligula tempor nulla, id laoreet magna lorem non mauris. Cras ac eros et lacus facilisis consequat. Mauris rhoncus augue et nunc eleifend volutpat. Ut sed justo sed elit rutrum congue. Pellentesque euismod tortor sed nibh vestibulum, nec elementum purus dictum. In hac habitasse platea dictumst.</p>
            <p className="mx-auto leading-relaxed text-base mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Curabitur pulvinar varius purus vel bibendum. Ut lobortis libero vitae ligula pharetra interdum. Sed nec nisi ac magna congue scelerisque. Aenean eget tellus nec odio faucibus luctus a et nulla. Proin nec ipsum vel magna scelerisque tincidunt. Ut at ex ut urna vehicula bibendum. Integer lacinia ipsum a est molestie, vel lacinia magna aliquet. Mauris posuere ex nec mauris dignissim, sit amet facilisis elit consequat. Proin aliquet augue eget libero volutpat, nec laoreet orci ullamcorper. Nunc sed ipsum in purus aliquam ultricies. Vivamus elementum consectetur purus, vitae luctus nisi vulputate et. Vivamus eu turpis et turpis tempus scelerisque. Sed consequat scelerisque risus. Vivamus dapibus augue sed odio fermentum, quis commodo justo rutrum. Sed feugiat metus sit amet ex vulputate, nec scelerisque metus eleifend.</p>
        </div>
    )
}

export default About;